version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: albums
    ports:
      - '5438:5432'
    networks:
      - app
  app:
    build: 
      context: .
    ports:
      - '8080:8080'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: albums
      POSTGRES_ADDR: db:5432
    networks:
      - app
networks:
  app: